[connections.snowflake]
account = "xxxxxxx-xxxxxxxx"
user = "your_username"
password = "xxxxxxxxxx"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "AVALANCHE_DB"
schema = "AVALANCHE_SCHEMA"s